spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: '1000'


  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB

  thymeleaf:
    cache: 'false'

  datasource:
    url: jdbc:mysql://localhost:3307/bean?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'gwang_1'

server:
  port: '80'

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

itemImgLocation: E:/bean_shop/item

uploadPath: file:///E:/bean_shop/



